########
# Dockerfile to build mysql:5.7 container images/
########
FROM mysql:5.7

MAINTAINER goncharova@ukr.net

RUN apt-get update

ENV MYSQL_ROOT_PASSWORD MyRootPassword
ENV MYSQL_DATABASE goncharova
ENV MYSQL_USER UserName
ENV MYSQL_PASSWORD MyUserPassword

EXPOSE 3306



