
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
  ubuntu.vm.box = "ubuntu/bionic64" 
  ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
  ubuntu.vm.synced_folder "/home/daria/012/hometask_5/Goncharova", "/home/vagrant/"
  ubuntu.vm.provision "shell",
  inline: "
    docker-compose up -d"

end
  
 

#  config.vm.define "centos" do |centos|
#  centos.vm.box = "centos/7"
#end

end
