---
# tasks file for role_b
- name: install epel
  yum:
    name: epel-release
    state: present
  tags: [apache2]

- name: install apache2
  yum:
    name: apache2
    state: present
  tags: [apache2]

- git:
   repo: https://github.com/11daria/012/hometask_8.git
   dest: /home/my login/hello
